on:
  workflow_dispatch:

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: Jahia/github-to-academy@v1
        with:
          files: docs/**/*.md
          graphql-endpoint: https://academy.jahia.com/modules/graphql
          graphql-authorization: ${{ secrets.GQL_AUTH }}
